### ISSUE TITLE
[FEATURE] Support HPA settings for worker nodes

### ISSUE THREAD

**Issue by tcodehuber** [apache/celeborn#2537]
### Is your feature request related to a problem? Please describe.
I wonder whether we can enable HPA feature for worker nodes. From the official docs, I could not find details about it.

### Describe alternatives you've considered

/cc @who-need-to-know

/assign @who-can-help-you

**Comment by SteNicholas** [comment]
@tcodehuber, please create JIRA ticket instead of issue.

**Comment by tcodehuber** [comment]
> I wonder whether we can enable HPA feature for worker nodes. From the official docs, I could not find details about it.

OK, refer to https://issues.apache.org/jira/browse/CELEBORN-1451
