### ISSUE TITLE
[BUG] default chart image doesn't work

### ISSUE THREAD

**Issue by aagumin** [apache/celeborn#2744]
### What is the bug(with logs or screenshots)?
default image for helm chart invalid

### How to reproduce the bug?
1. [Install helm chart in k8s](https://celeborn.apache.org/docs/latest/deploy_on_k8s/) with default config
get error 
```
/bin/sh: line 3: /opt/celeborn/sbin/start-master.sh: No such file or directory
```

**Comment by FMX** [comment]
You need to change the image to your latest image rather than use the default value. 
Celeborn doesn't have an official image repository.
I don't think this is a BUG, but I think it's worth changing the helm to tell users that do not use the default values.

**Comment by aagumin** [comment]
okey, i fixed this in my cluster, it's not a problem, but in docs i see this paragraph https://github.com/apache/celeborn/blob/main/docker/DEPLOY_ON_K8S.md#optional-build-celeborn-docker-image 
maybe fix this in doc? and add your comment in doc?

**Comment by SteNicholas** [comment]
@aagumin, you could follow the https://celeborn.apache.org/docs/latest/deploy_on_k8s/#4-check-celeborn.
